/*
   Design file. Includes Etching data structure, colours, and custom grids.
*/

import UIKit

// MARK: - Etching

/// The data structure used to store Etchings when loading and saving.
public struct Etching {
    public let title: String
    public let gridArray: [[UIColor]]

    public init(title: String, gridArray: [[UIColor]]) {
        self.title = title
        self.gridArray = gridArray
    }
}

// MARK: Colours

/// The set of colours used in the project.
public struct Colours {
    /// Brand colours used in UI.
    public static let brandWhite: UIColor = UIColor(red: 236 / 255, green: 252 / 255, blue: 246 / 255, alpha: 1)
    public static let brandPink: UIColor = UIColor(red: 250 / 255, green: 228 / 255, blue: 230 / 255, alpha: 1)
    public static let brandSalmon: UIColor = UIColor(red: 255 / 255, green: 205 / 255, blue: 182 / 255, alpha: 1)
    public static let brandBrown: UIColor = UIColor(red: 35 / 255, green: 26 / 255, blue: 19 / 255, alpha: 1)

    /// Colours to use in colour palette.
    public static let black: UIColor = UIColor(red: 0 / 255, green: 0 / 255, blue: 0 / 255, alpha: 1)
    public static let blue: UIColor = UIColor(red: 0 / 255, green: 0 / 255, blue: 255 / 255, alpha: 1)
    public static let red: UIColor = UIColor(red: 255 / 255, green: 0 / 255, blue: 0 / 255, alpha: 1)
    public static let tan: UIColor = UIColor(red: 203 / 255, green: 255 / 255, blue: 101 / 255, alpha: 1)
    public static let darkGreen: UIColor = UIColor(red: 0 / 255, green: 127 / 255, blue: 0 / 255, alpha: 1)
    public static let lightGreen: UIColor = UIColor(red: 0 / 255, green: 255 / 255, blue: 0 / 255, alpha: 1)
    public static let yellow: UIColor = UIColor(red: 255 / 255, green: 255 / 255, blue: 0 / 255, alpha: 1)
    public static let white: UIColor = UIColor(red: 255 / 255, green: 255 / 255, blue: 255 / 255, alpha: 1)
    public static let gray: UIColor = UIColor(red: 127 / 255, green: 127 / 255, blue: 127 / 255, alpha: 1)
    public static let cyan: UIColor = UIColor(red: 0 / 255, green: 255 / 255, blue: 255 / 255, alpha: 1)
    public static let orange: UIColor = UIColor(red: 255 / 255, green: 159 / 255, blue: 0 / 255, alpha: 1)
    public static let brown: UIColor = UIColor(red: 127 / 255, green: 127 / 255, blue: 0 / 255, alpha: 1)
    public static let pink: UIColor = UIColor(red: 255 / 255, green: 63 / 255, blue: 255 / 255, alpha: 1)
    public static let violet: UIColor = UIColor(red: 127 / 255, green: 127 / 255, blue: 255 / 255, alpha: 1)
    public static let brightGreen: UIColor = UIColor(red: 127 / 255, green: 255 / 255, blue: 0 / 255, alpha: 1)
    public static let magenta: UIColor = UIColor(red: 255 / 255, green: 0 / 255, blue: 127 / 255, alpha: 1)
}

// MARK: - CustomDesigns

/// Custom Etchings used in the gallery. All art is based on a 32x32 bit grid. Reference sources are linked above pixel arrays.
public struct CustomDesigns {

    public var array: [Etching] = [Etching]()

    public init() {
        let custom1 = Etching(title: "Batman Logo", gridArray: custom1Array)
        array.append(custom1)

        let custom2 = Etching(title: "Apple Logo", gridArray: custom2Array)
        array.append(custom2)

        let custom3 = Etching(title: "Deadpool", gridArray: custom3Array)
        array.append(custom3)

        let custom4 = Etching(title: "Super Mario", gridArray: custom4Array)
        array.append(custom4)

        let custom5 = Etching(title: "Soccer Ball", gridArray: custom5Array)
        array.append(custom5)

        let custom6 = Etching(title: "Poke Ball", gridArray: custom6Array)
        array.append(custom6)
    }

    /// NOTE: All images are rotated right and flipped horizontally to translate to the grid correctly.

    /// Source: https://www.brik.co/blogs/pixel-art/173921927-batman-logo-pixel-art
    private let custom1Array: [[UIColor]] = [
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white]
    ]

    /// Source: https://www.pinterest.ca/pin/213780313536281766/
    private let custom2Array: [[UIColor]] = [
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.orange, Colours.orange, Colours.orange, Colours.orange, Colours.red, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.cyan, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.yellow, Colours.yellow, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.red, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.cyan, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.yellow, Colours.yellow, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.cyan, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.lightGreen, Colours.yellow, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.violet, Colours.violet, Colours.violet, Colours.violet, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.violet, Colours.violet, Colours.violet, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white]
    ]

    /// Source: https://cdn.apps.joltteam.com/brikbuild/deadpool-pixel-art-8bit-antihero-deadpool-marvel-masked-vigilante-pixel-pixel-art-superhero-5a24f9baf6c96a8d29720b39.template-32x32.jpg
    private let custom3Array: [[UIColor]] = [
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.brown, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.brown, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.brown, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.red, Colours.red, Colours.gray, Colours.red, Colours.red, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.brown, Colours.black, Colours.white, Colours.white, Colours.black, Colours.black, Colours.gray, Colours.gray, Colours.red, Colours.red, Colours.red, Colours.gray, Colours.red, Colours.red, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.gray, Colours.red, Colours.red, Colours.gray, Colours.gray, Colours.red, Colours.red, Colours.gray, Colours.red, Colours.red, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.black, Colours.gray, Colours.gray, Colours.black, Colours.gray, Colours.red, Colours.red, Colours.gray, Colours.black, Colours.black, Colours.black, Colours.red, Colours.red, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.white, Colours.black, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.red, Colours.black, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.black, Colours.gray, Colours.black, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.gray, Colours.gray, Colours.white],
        [Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.gray, Colours.gray, Colours.gray, Colours.red, Colours.red, Colours.red, Colours.black, Colours.gray, Colours.black, Colours.black, Colours.gray, Colours.gray, Colours.gray, Colours.black, Colours.black, Colours.black, Colours.gray, Colours.gray, Colours.gray, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.red, Colours.red, Colours.black, Colours.gray, Colours.gray, Colours.gray, Colours.black, Colours.gray, Colours.gray, Colours.gray, Colours.black, Colours.gray, Colours.gray, Colours.gray, Colours.red, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.gray, Colours.gray, Colours.white, Colours.white, Colours.gray, Colours.gray, Colours.red, Colours.red, Colours.black, Colours.red, Colours.red, Colours.black, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.black, Colours.gray, Colours.red, Colours.red, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.gray, Colours.gray, Colours.white, Colours.white, Colours.gray, Colours.gray, Colours.red, Colours.red, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.gray, Colours.gray, Colours.red, Colours.red, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.gray, Colours.gray, Colours.white, Colours.gray, Colours.gray, Colours.red, Colours.red, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.black, Colours.red, Colours.red, Colours.black, Colours.white],
        [Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.red, Colours.red, Colours.red, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.red, Colours.red, Colours.black, Colours.red, Colours.black, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.red, Colours.black, Colours.white, Colours.black, Colours.gray, Colours.gray, Colours.black, Colours.gray, Colours.gray, Colours.gray, Colours.gray, Colours.black, Colours.black, Colours.gray, Colours.gray, Colours.gray, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.red, Colours.red, Colours.red, Colours.gray, Colours.gray, Colours.gray, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.gray, Colours.red, Colours.red, Colours.gray, Colours.red, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.red, Colours.red, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white]
    ]

    /// Source: https://www.brik.co/blogs/pixel-art/super-mario-pixel-art-1
    private let custom4Array: [[UIColor]] = [
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.gray, Colours.gray, Colours.gray, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.brown, Colours.brown, Colours.brown, Colours.white, Colours.white, Colours.red, Colours.red, Colours.gray, Colours.gray, Colours.gray, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.brown, Colours.tan, Colours.tan, Colours.brown, Colours.white, Colours.red, Colours.red, Colours.red, Colours.red, Colours.gray, Colours.blue, Colours.blue, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.red, Colours.brown, Colours.brown, Colours.brown, Colours.tan, Colours.tan, Colours.red, Colours.red, Colours.red, Colours.blue, Colours.blue, Colours.blue, Colours.blue, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.red, Colours.brown, Colours.tan, Colours.brown, Colours.tan, Colours.tan, Colours.blue, Colours.blue, Colours.blue, Colours.yellow, Colours.blue, Colours.blue, Colours.blue, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.red, Colours.tan, Colours.tan, Colours.tan, Colours.tan, Colours.tan, Colours.red, Colours.red, Colours.blue, Colours.blue, Colours.blue, Colours.blue, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.red, Colours.tan, Colours.tan, Colours.tan, Colours.tan, Colours.tan, Colours.red, Colours.red, Colours.blue, Colours.blue, Colours.blue, Colours.blue, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.red, Colours.black, Colours.black, Colours.tan, Colours.black, Colours.tan, Colours.red, Colours.blue, Colours.blue, Colours.yellow, Colours.blue, Colours.blue, Colours.blue, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.tan, Colours.tan, Colours.black, Colours.black, Colours.tan, Colours.red, Colours.red, Colours.red, Colours.blue, Colours.blue, Colours.blue, Colours.blue, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.white, Colours.tan, Colours.tan, Colours.black, Colours.tan, Colours.white, Colours.red, Colours.red, Colours.red, Colours.gray, Colours.blue, Colours.blue, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.white, Colours.tan, Colours.tan, Colours.black, Colours.white, Colours.white, Colours.red, Colours.red, Colours.gray, Colours.gray, Colours.gray, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.tan, Colours.white, Colours.white, Colours.white, Colours.white, Colours.red, Colours.gray, Colours.gray, Colours.gray, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white]
    ]

    /// Source: https://www.brik.co/blogs/pixel-art/soccer-ball
    private let custom5Array: [[UIColor]] = [
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.black, Colours.black, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.black, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white],
        [Colours.black, Colours.black, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white],
        [Colours.black, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white],
        [Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white],
        [Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white],
        [Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white],
        [Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white],
        [Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white],
        [Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white],
        [Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white],
        [Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white],
        [Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white],
        [Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white],
        [Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white],
        [Colours.black, Colours.black, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white],
        [Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white]
    ]

    /// Source: https://line.17qq.com/articles/ccwahqcqx.html
    private let custom6Array: [[UIColor]] = [
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.red, Colours.red, Colours.black, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.white, Colours.red, Colours.red, Colours.red, Colours.black, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.white, Colours.white, Colours.white, Colours.red, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.white, Colours.red, Colours.black, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.red, Colours.red, Colours.red, Colours.red, Colours.red, Colours.black, Colours.white, Colours.white, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.red, Colours.red, Colours.black, Colours.white, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.black, Colours.black, Colours.black, Colours.black, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white],
        [Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white, Colours.white]
    ]
}
